"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

env = environ.Env()
environ.Env.read_env(BASE_DIR / ".env")

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    "kakeibo",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # 静的ファイル（Admin/Chart.js等）をgunicornから直接配信する（本番、7.4節: デプロイの自動化）。
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    # 要件4.9.3: 未認証状態ではログイン画面を除く全ページへのアクセスを拒否する。
    # 個別ビューを認証不要にする場合は @login_not_required を明示する。
    "django.contrib.auth.middleware.LoginRequiredMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "ja"

TIME_ZONE = "Asia/Tokyo"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# 認証（要件4.9、基本設計書6.4節）

AUTH_USER_MODEL = "kakeibo.User"

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]

SITE_ID = 1

LOGIN_URL = "account_login"
LOGIN_REDIRECT_URL = "dashboard"
LOGOUT_REDIRECT_URL = "account_login"

ACCOUNT_ADAPTER = "kakeibo.adapters.AccountAdapter"
SOCIALACCOUNT_ADAPTER = "kakeibo.adapters.SocialAccountAdapter"

# kakeibo.Userはusernameフィールドを持たないため、allauthにその旨を明示する。
# 未設定（既定値"username"）のままだと、ログイン後メッセージ表示等でuser.usernameを
# 参照しAttributeErrorになる（Noneの場合はUser.__str__=display_nameにフォールバックする）。
ACCOUNT_USER_MODEL_USERNAME_FIELD = None

# ローカルのメール/パスワードによるサインアップ・ログインは提供せず、Google OAuthのみを許可する。
# ローカルサインアップ画面自体はAccountAdapter.is_open_for_signupで到達不可にしているが、
# ACCOUNT_LOGIN_METHODSのemailと矛盾しない構成にしてallauthのシステムチェック警告
# （account.W001）を解消する。
ACCOUNT_LOGIN_METHODS = {"email"}
ACCOUNT_SIGNUP_FIELDS = ["email*"]
ACCOUNT_EMAIL_VERIFICATION = "none"
SOCIALACCOUNT_AUTO_SIGNUP = False
SOCIALACCOUNT_LOGIN_ON_GET = True
SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "APP": {
            "client_id": env("GOOGLE_OAUTH_CLIENT_ID"),
            "secret": env("GOOGLE_OAUTH_CLIENT_SECRET"),
            "key": "",
        },
        "SCOPE": ["profile", "email"],
        "AUTH_PARAMS": {"access_type": "online"},
    },
}

# 要件4.9.6: セッションには有効期限を設け、一定時間の無操作で再認証を求める。
SESSION_COOKIE_AGE = env.int("SESSION_TIMEOUT_SECONDS", default=1800)
SESSION_SAVE_EVERY_REQUEST = True

# Gmail API（メール取込・通知、基本設計書6.1節）。
# ログイン認証（Google OAuth、AUTHENTICATION_BACKENDS）とは別のOAuthクライアントを使用する。
GMAIL_API_CLIENT_ID = env("GMAIL_API_CLIENT_ID", default="")
GMAIL_API_CLIENT_SECRET = env("GMAIL_API_CLIENT_SECRET", default="")
GMAIL_API_REFRESH_TOKEN = env("GMAIL_API_REFRESH_TOKEN", default="")

# 通知（要件6.5.1、基本設計書7.4節）: エラー発生時の通知メール送信先。
NOTIFICATION_RECIPIENT_EMAIL = env("NOTIFICATION_RECIPIENT_EMAIL", default="")

# メール取込バッチ（基本設計書6.2節）で登録する取引のcreated_by（登録者）として扱う利用者。
MAIL_IMPORT_USER_EMAIL = env("MAIL_IMPORT_USER_EMAIL", default="")
