# Generated by Django 5.2.17 on 2026-08-13 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('account_type', models.CharField(choices=[('bank', '銀行'), ('securities', '証券'), ('emoney', '電子マネー'), ('cash', '現金'), ('other', 'その他')], max_length=20)),
                ('currency', models.CharField(default='JPY', max_length=3)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmail_message_id', models.CharField(max_length=100, unique=True)),
                ('service', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('success', '成功'), ('failed', '失敗')], max_length=20)),
                ('error_detail', models.CharField(blank=True, max_length=500, null=True)),
                ('executed_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_sub', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('admin', '管理者'), ('general', '一般')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category_type', models.CharField(choices=[('expense', '支出'), ('income', '収入')], max_length=20)),
                ('monthly_budget', models.IntegerField(blank=True, null=True)),
                ('is_aggregated', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('name', 'category_type'), name='uq_category_name_type')],
            },
        ),
        migrations.CreateModel(
            name='FixedIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('start_month', models.DateField()),
                ('end_month', models.DateField(blank=True, null=True)),
                ('memo', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kakeibo.account')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kakeibo.category')),
            ],
        ),
        migrations.CreateModel(
            name='FixedCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payee', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('start_month', models.DateField()),
                ('end_month', models.DateField(blank=True, null=True)),
                ('memo', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kakeibo.category')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kakeibo.paymentmethod')),
            ],
        ),
        migrations.CreateModel(
            name='StoreRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100, unique=True)),
                ('priority', models.IntegerField()),
                ('is_auto_generated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kakeibo.category')),
            ],
        ),
        migrations.CreateModel(
            name='BalanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_date', models.DateField()),
                ('balance', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kakeibo.account')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('account', 'recorded_date'), name='uq_balance_record_account_date')],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('expense', '支出'), ('income', '収入')], max_length=20)),
                ('transaction_date', models.DateField(db_index=True)),
                ('amount', models.IntegerField()),
                ('counterpart', models.CharField(max_length=100)),
                ('memo', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.CharField(choices=[('mail', 'メール取込'), ('manual', '手動入力')], max_length=20)),
                ('dedup_hash', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('is_excluded_from_aggregation', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kakeibo.account')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kakeibo.category')),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kakeibo.paymentmethod')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kakeibo.user')),
            ],
            options={
                'indexes': [models.Index(fields=['transaction_type'], name='kakeibo_tra_transac_a706d2_idx')],
            },
        ),
    ]
