# Generated by Django 5.2.17 on 2026-09-12 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0002_user_last_login_user_password_alter_user_google_sub_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': '口座', 'verbose_name_plural': '口座'},
        ),
        migrations.AlterModelOptions(
            name='balancerecord',
            options={'verbose_name': '残高記録', 'verbose_name_plural': '残高記録'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'カテゴリ', 'verbose_name_plural': 'カテゴリ'},
        ),
        migrations.AlterModelOptions(
            name='emailimportlog',
            options={'verbose_name': 'メール取込ログ', 'verbose_name_plural': 'メール取込ログ'},
        ),
        migrations.AlterModelOptions(
            name='fixedcost',
            options={'verbose_name': '固定費', 'verbose_name_plural': '固定費'},
        ),
        migrations.AlterModelOptions(
            name='fixedincome',
            options={'verbose_name': '固定収入', 'verbose_name_plural': '固定収入'},
        ),
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'verbose_name': '決済手段', 'verbose_name_plural': '決済手段'},
        ),
        migrations.AlterModelOptions(
            name='storerule',
            options={'verbose_name': '店舗ルール', 'verbose_name_plural': '店舗ルール'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': '取引', 'verbose_name_plural': '取引'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '利用者', 'verbose_name_plural': '利用者'},
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('bank', '銀行'), ('securities', '証券'), ('emoney', '電子マネー'), ('cash', '現金'), ('other', 'その他')], max_length=20, verbose_name='種別'),
        ),
        migrations.AlterField(
            model_name='account',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='account',
            name='currency',
            field=models.CharField(default='JPY', max_length=3, verbose_name='通貨'),
        ),
        migrations.AlterField(
            model_name='account',
            name='display_order',
            field=models.IntegerField(default=0, verbose_name='表示順'),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='有効'),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=50, verbose_name='口座名'),
        ),
        migrations.AlterField(
            model_name='account',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='balancerecord',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kakeibo.account', verbose_name='口座'),
        ),
        migrations.AlterField(
            model_name='balancerecord',
            name='balance',
            field=models.IntegerField(verbose_name='残高'),
        ),
        migrations.AlterField(
            model_name='balancerecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='balancerecord',
            name='recorded_date',
            field=models.DateField(verbose_name='記録日'),
        ),
        migrations.AlterField(
            model_name='balancerecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('expense', '支出'), ('income', '収入')], max_length=20, verbose_name='種別'),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='category',
            name='display_order',
            field=models.IntegerField(default=0, verbose_name='表示順'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_aggregated',
            field=models.BooleanField(default=True, verbose_name='集計対象'),
        ),
        migrations.AlterField(
            model_name='category',
            name='monthly_budget',
            field=models.IntegerField(blank=True, null=True, verbose_name='月次予算'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, verbose_name='カテゴリ名'),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='emailimportlog',
            name='error_detail',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='エラー詳細'),
        ),
        migrations.AlterField(
            model_name='emailimportlog',
            name='executed_at',
            field=models.DateTimeField(verbose_name='実行日時'),
        ),
        migrations.AlterField(
            model_name='emailimportlog',
            name='gmail_message_id',
            field=models.CharField(max_length=100, unique=True, verbose_name='Gmailメッセージ ID'),
        ),
        migrations.AlterField(
            model_name='emailimportlog',
            name='service',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='サービス'),
        ),
        migrations.AlterField(
            model_name='emailimportlog',
            name='status',
            field=models.CharField(choices=[('success', '成功'), ('failed', '失敗')], max_length=20, verbose_name='ステータス'),
        ),
        migrations.AlterField(
            model_name='fixedcost',
            name='amount',
            field=models.IntegerField(verbose_name='金額'),
        ),
        migrations.AlterField(
            model_name='fixedcost',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kakeibo.category', verbose_name='カテゴリ'),
        ),
        migrations.AlterField(
            model_name='fixedcost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='fixedcost',
            name='end_month',
            field=models.DateField(blank=True, null=True, verbose_name='終了月'),
        ),
        migrations.AlterField(
            model_name='fixedcost',
            name='memo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='メモ'),
        ),
        migrations.AlterField(
            model_name='fixedcost',
            name='payee',
            field=models.CharField(max_length=100, verbose_name='支払先'),
        ),
        migrations.AlterField(
            model_name='fixedcost',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kakeibo.paymentmethod', verbose_name='決済手段'),
        ),
        migrations.AlterField(
            model_name='fixedcost',
            name='start_month',
            field=models.DateField(verbose_name='開始月'),
        ),
        migrations.AlterField(
            model_name='fixedcost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='fixedincome',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kakeibo.account', verbose_name='入金先口座'),
        ),
        migrations.AlterField(
            model_name='fixedincome',
            name='amount',
            field=models.IntegerField(verbose_name='金額'),
        ),
        migrations.AlterField(
            model_name='fixedincome',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kakeibo.category', verbose_name='カテゴリ'),
        ),
        migrations.AlterField(
            model_name='fixedincome',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='fixedincome',
            name='end_month',
            field=models.DateField(blank=True, null=True, verbose_name='終了月'),
        ),
        migrations.AlterField(
            model_name='fixedincome',
            name='memo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='メモ'),
        ),
        migrations.AlterField(
            model_name='fixedincome',
            name='source',
            field=models.CharField(max_length=100, verbose_name='収入元'),
        ),
        migrations.AlterField(
            model_name='fixedincome',
            name='start_month',
            field=models.DateField(verbose_name='開始月'),
        ),
        migrations.AlterField(
            model_name='fixedincome',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='display_order',
            field=models.IntegerField(default=0, verbose_name='表示順'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='有効'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='決済手段名'),
        ),
        migrations.AlterField(
            model_name='storerule',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kakeibo.category', verbose_name='カテゴリ'),
        ),
        migrations.AlterField(
            model_name='storerule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='storerule',
            name='is_auto_generated',
            field=models.BooleanField(default=False, verbose_name='自動生成'),
        ),
        migrations.AlterField(
            model_name='storerule',
            name='keyword',
            field=models.CharField(max_length=100, unique=True, verbose_name='キーワード'),
        ),
        migrations.AlterField(
            model_name='storerule',
            name='priority',
            field=models.IntegerField(verbose_name='優先度'),
        ),
        migrations.AlterField(
            model_name='storerule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kakeibo.account', verbose_name='入金先口座'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.IntegerField(verbose_name='金額'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kakeibo.category', verbose_name='カテゴリ'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='counterpart',
            field=models.CharField(max_length=100, verbose_name='店舗名・収入元'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='登録者'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='dedup_hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='重複判定ハッシュ'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='削除済み'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='is_excluded_from_aggregation',
            field=models.BooleanField(default=False, verbose_name='除外フラグ'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='memo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='メモ'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kakeibo.paymentmethod', verbose_name='決済手段'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='source',
            field=models.CharField(choices=[('mail', 'メール取込'), ('manual', '手動入力')], max_length=20, verbose_name='取込元'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateField(db_index=True, verbose_name='日付'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('expense', '支出'), ('income', '収入')], max_length=20, verbose_name='種別'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='user',
            name='display_name',
            field=models.CharField(max_length=100, verbose_name='表示名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='メールアドレス'),
        ),
        migrations.AlterField(
            model_name='user',
            name='google_sub',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Google識別子'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='有効'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', '管理者'), ('general', '一般')], default='general', max_length=20, verbose_name='権限'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
    ]
